### ISSUE TITLE
Connection refuse issue

### ISSUE THREAD

**Issue by npsonis** [antonisdim/haystac#13]
Hi, 
I get the following when trying to build a database.
[bgzip] Could not open ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/430/045/GCF_000430045.1_ASM43004v1/GCF_000430045.1_ASM43004v1_genomic.fna.gz: Connection refused
haystac: error: Unable to download assembly ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/430/045/GCF_000430045.1_ASM43004v1/GCF_000430045.1_ASM43004v1_genomic.fna.gz
None

Any thoughts?

Also the step "Job 4: Splitting the representative RefSeq table in smaller tables." takes too long every time that I need to make a different database. Since it is the same, is there a way to perform it once, store the smaller tables locally and use them in next database builds?

Finally, please consider to incorporate a new argument that will output the number and which genomes are going to be downoaded at the end, without actually downloading anything. This will help evaluate if a taxon is missing.

**Comment by npsonis** [comment]
Thanks Antony,

the connection error persists but I think it is due to my institute's firewall. Is there a way to work around it own my own? If not, and if I just have to ask my admin, then you may close this issue.

Regarding the second point made, I guess that an option may be added for someone that does not care about the plasmids in order to save time.  

Best,

Nikos

**Comment by antonisdim** [comment]
Hello Nikos, 

I hope you are well !

The best I can think of is if you download the sequence you need manually from NCBI and then point to its location using the ``--sequences-file`` flag. 

That's a great suggestion actually, and we'll definitely try our best to incorporate it in a future version of ``haystac``. Again thank you for your patience, your suggestions and of course for using ``haystac``.

Please do let me know if you run into any other issues !

Best, 
Antony
