### ISSUE TITLE
HAYSTAC not working on UBUNTU 16.04.7 LTS

### ISSUE THREAD

**Issue by eugeniosss** [antonisdim/haystac#16]
Hello,

I have worked with HAYSTAC previously on another OS (Red Hat) and had no big problems. However, now I am trying to use it on another OS, Ubuntu 16.04.7, and it seems to not be working. First, I tried to install it via mamba. I was able to do so. However, when I tried to create a database, the program failed to do so, as it got an error. I am attaching the log file.

I got the impression I got an error because of some dependencies. So I tried to install the dependencies you asked for in a separate environment. I failed to do so, conda claimed there were incompatibilities. So I tried to see which was causing conflicts by installing one dependency at the time. I discovered I am able to install all dependencies, unless this one:

snakemake==6.3.0

Any idea what problem I am facing? And how should I proceed? I know I am working with an outdated Ubuntu version, however I am working on a cluster, thus I cannot update it.

Best,
Eugénio

[2023-02-15T162611.158424.snakemake.log](https://github.com/antonisdim/haystac/files/10745695/2023-02-15T162611.158424.snakemake.log)

**Comment by antonisdim** [comment]
Hello Eugenio, 

I hope you are doing great and thank you for posting this !

I will have a look at it this week and get back to you ASAP. 

Thank you for your patience !

Best, 
Antony

**Comment by antonisdim** [comment]
Hello Eugenio, 

I hope you are well !

Unfortunately I am not able tor reproduce this error. Have you tried installing the newest version of ``haystac`` and see if the problem persists ? 

If the problem is still persisting, would it be easy for you to run the newest version of ``haystac`` with the ``--debug`` flag activated and let know what the output is ?

Thank you for your help !

Best,
Antony

**Comment by eugeniosss** [comment]
Hello Antony,

Thank you very much for your time and help!

With this new version of haystac I was already able to install and run haystac on this machine!

Best,
Eugénio
