### ISSUE TITLE
Error in compileCode when running mapDamage

### ISSUE THREAD

**Issue by Fishball99** [antonisdim/haystac#22]
This is my script:
`haystac sample \
        --fastq-r1 "/data1/user/zhaozh/2.PIG/1.screen/10.CSSS_230928/rawdata/X101SC23023451-Z01-J242/01.RawData/SS16/SS16_1.fq.gz" \
        --fastq-r2 "/data1/user/zhaozh/2.PIG/1.screen/10.CSSS_230928/rawdata/X101SC23023451-Z01-J242/01.RawData/SS16/SS16_2.fq.gz" \
        --output "Sample_SS16" \
        --cores 64 \
        --mem 102400 \
        --collapse True

haystac analyse --mode abundances \
        --database /data1/user/yuwq/haystac_db2/pathogen20240321/ \
        --sample "Sample_SS16" \
        --output "Output_SS16" \
        --aDNA \
        --cores 64 \
        --mem 102400`

Error printed in snakemake log is here:
[Mon Jun 10 15:49:25 2024]
Error in rule run_mapdamage:
    jobid: 1069
    output: /data1/user/yuwq/haystac_db2/Output_ZJSS026/mapdamage/Sample_ZJSS026/COLLAPSED/Trypanosoma_cruzi/GCF_000209065.1
    log: /data1/user/yuwq/haystac_db2/Output_ZJSS026/mapdamage/Sample_ZJSS026/COLLAPSED/Trypanosoma_cruzi_GCF_000209065.1.log (check log file(s) for error message)
    conda-env: /data1/user/yuwq/haystac/cache/conda/f6339089f4a4ca604fcdb438cc255db4
    shell:
        mapDamage -i /data1/user/yuwq/haystac_db2/Output_ZJSS026/rmdup_bam/Sample_ZJSS026/COLLAPSED/Trypanosoma_cruzi/Trypanosoma_cruzi_GCF_000209065.1_dirichlet_COLLAPSED_rmdup.bam -r /data1/user/yuwq/haystac/cache/ncbi/Trypanosoma_cruzi/GCF_000209065.1.fasta.gz -d /data1/user/yuwq/haystac_db2/Output_ZJSS026/mapdamage/Sample_ZJSS026/COLLAPSED/Trypanosoma_cruzi/GCF_000209065.1 2> /data1/user/yuwq/haystac_db2/Output_ZJSS026/mapdamage/Sample_ZJSS026/COLLAPSED/Trypanosoma_cruzi_GCF_000209065.1.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job run_mapdamage since they might be corrupted:

And the detailed content of log is here:
Started with the command: /data1/user/yuwq/haystac/cache/conda/f6339089f4a4ca604fcdb438cc255db4/bin/mapDamage -i /data1/user/yuwq/haystac_db2/Output_ZJSS026/rmdup_bam/Sample_ZJSS026/COLLAPSED/Trypanosoma_cruzi/Trypanosoma_cruzi_GCF_000209065.1_dirichlet_COLLAPSED_rmdup.bam -r /data1/user/yuwq/haystac/cache/ncbi/Trypanosoma_cruzi/GCF_000209065.1.fasta.gz -d /data1/user/yuwq/haystac_db2/Output_ZJSS026/mapdamage/Sample_ZJSS026/COLLAPSED/Trypanosoma_cruzi/GCF_000209065.1
Performing Bayesian estimates
Error in compileCode(f, code, language = language, verbose = verbose) :
  Compilation ERROR, function(s)/method(s) not created! Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() :
  argument is of length zero
Calls: <Anonymous> -> .shlib_internal
Execution halted
Calls: source ... withVisible -> eval -> eval -> cxxfunction -> compileCode
In addition: Warning messages:
1: package ‘foreach’ was built under R version 4.0.5
2: package ‘RcppGSL’ was built under R version 4.0.5
3: In system(cmd, intern = !verbose) :
  running command '/data1/user/yuwq/haystac/cache/conda/f6339089f4a4ca604fcdb438cc255db4/lib/R/bin/R CMD SHLIB file1a5d6179c6e26.cpp 2> file1a5d6179c6e26.cpp.err.txt' had status 1
The Bayesian statistics program failed to finish
Traceback (most recent call last):
  File "/data1/user/yuwq/haystac/cache/conda/f6339089f4a4ca604fcdb438cc255db4/bin/mapDamage", line 371, in <module>
    sys.exit(main())
  File "/data1/user/yuwq/haystac/cache/conda/f6339089f4a4ca604fcdb438cc255db4/bin/mapDamage", line 354, in main
    mapdamage.rscript.run_stats(options)
  File "/data1/user/yuwq/haystac/cache/conda/f6339089f4a4ca604fcdb438cc255db4/lib/python3.9/site-packages/mapdamage/rscript.py", line 142, in run_stats
    raise e
  File "/data1/user/yuwq/haystac/cache/conda/f6339089f4a4ca604fcdb438cc255db4/lib/python3.9/site-packages/mapdamage/rscript.py", line 139, in run_stats
    check_call(arg)
  File "/data1/user/yuwq/haystac/cache/conda/f6339089f4a4ca604fcdb438cc255db4/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['Rscript', '/data1/user/yuwq/haystac/cache/conda/f6339089f4a4ca604fcdb438cc255db4/lib/python3.9/site-packages/mapdamage/Rscripts/stats/runGeneral.R', '--args', '30', '10000', '10', '50000', '0', '0', '1', '1', '0', '0', '1', '12', '/data1/user/yuwq/haystac_db2/Output_ZJSS026/mapdamage/Sample_ZJSS026/COLLAPSED/Trypanosoma_cruzi/GCF_000209065.1/', '/data1/user/yuwq/haystac/cache/conda/f6339089f4a4ca604fcdb438cc255db4/lib/python3.9/site-packages/mapdamage/Rscripts/stats/', '/data1/user/yuwq/haystac_db2/Output_ZJSS026/mapdamage/Sample_ZJSS026/COLLAPSED/Trypanosoma_cruzi/GCF_000209065.1/Stats_out', '0', '0', '0', '/data1/user/yuwq/haystac_db2/Output_ZJSS026/mapdamage/Sample_ZJSS026/COLLAPSED/Trypanosoma_cruzi/GCF_000209065.1/acgt_ratio.csv', '0', '0']' returned non-zero exit status 1.

Thank you for your response!

**Comment by antonisdim** [comment]
Hello, 

I am really sorry for the delay ! I'll have a look this week and get back to you ASAP. 

Thank you !

**Comment by Fishball99** [comment]
Thank you,

Looking forward to your response!

**Comment by antonisdim** [comment]
Hello Fishball99, 

I hope you are well and apologies for not getting back to you sooner. 

I have been updating some of ``haystac``'s dependencies this past month in preparation of its next version, and I have been running some tests in two different systems. Unfortunately I have not been able tor reproduce the ``mapdamage`` error you have posted. 

Are you possibly trying to run this on a macOS machine (maybe the M chip series) ? If yes, then possibly that might be the cause of the error (see this post from ``stackoverflow`` where a user had a similar problem https://stackoverflow.com/questions/53813323/installing-r-packages-in-macos-mojave-error-in-if-nzcharshlib-libadd). Possibly their solution could fix your compilation error. 

I'll keep an eye out though for sure in case I can find a better solution. Please let me know if you encounter any other bugs, and thank you for patience !

Best, 
A

**Comment by Fishball99** [comment]
Thank you for your response! Looking forward to the next version.
